import type { FontAnalysis, PairingCritique } from './types';
import { jsPDF } from 'jspdf';
import { isProfessional } from './services/tierService';

// Helper to convert font name to valid CSS variable name
const toSlug = (name: string): string => {
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
};

// Helper to extract weight number from recommendation string
const extractWeight = (rec: string): number => {
  const match = rec.match(/\d+/);
  return match ? parseInt(match[0], 10) : 400;
};

/**
 * Generate CSS variables for a font analysis
 */
export function generateCSSVariables(analysis: FontAnalysis): string {
  const slug = toSlug(analysis.fontName);
  const weights = analysis.weightRecommendations.map(rec => {
    const weight = extractWeight(rec);
    const label = rec.split(' ')[0].toLowerCase();
    return `  --font-weight-${slug}-${label}: ${weight};`;
  });

  return `/* ${analysis.fontName} - CSS Variables */
/* Generated by FontPair AI */

:root {
  /* Font Family */
  --font-family-${slug}: "${analysis.fontName}", ${analysis.fontType.toLowerCase().includes('serif') && !analysis.fontType.toLowerCase().includes('sans') ? 'serif' : 'sans-serif'};

  /* Font Weights */
${weights.join('\n')}

  /* Usage Notes */
  /* Type: ${analysis.fontType} */
  /* Designer: ${analysis.designer} */
  /* Best for: ${analysis.usageRecommendations.slice(0, 2).join(', ')} */
}

/* Example Usage */
.heading-${slug} {
  font-family: var(--font-family-${slug});
  font-weight: var(--font-weight-${slug}-bold, 700);
}

.body-${slug} {
  font-family: var(--font-family-${slug});
  font-weight: var(--font-weight-${slug}-regular, 400);
}`;
}

/**
 * Generate Tailwind CSS config for a font analysis
 */
export function generateTailwindConfig(analysis: FontAnalysis): string {
  const slug = toSlug(analysis.fontName);
  const fallback = analysis.fontType.toLowerCase().includes('serif') && !analysis.fontType.toLowerCase().includes('sans')
    ? 'ui-serif, Georgia, serif'
    : 'ui-sans-serif, system-ui, sans-serif';

  return `// ${analysis.fontName} - Tailwind CSS Configuration
// Generated by FontPair AI

// Add to your tailwind.config.js:

module.exports = {
  theme: {
    extend: {
      fontFamily: {
        '${slug}': ['"${analysis.fontName}"', '${fallback}'],
      },
      // Optional: Add as a font weight utility
      fontWeight: {
        // Based on analysis recommendations
${analysis.weightRecommendations.map(rec => {
  const weight = extractWeight(rec);
  const label = rec.split(' ')[0].toLowerCase();
  return `        '${slug}-${label}': '${weight}',`;
}).join('\n')}
      },
    },
  },
}

// Usage in your HTML/JSX:
// <h1 class="font-${slug} font-bold">Heading</h1>
// <p class="font-${slug}">Body text</p>

// Don't forget to import the font in your CSS:
// @import url('https://fonts.googleapis.com/css2?family=${analysis.fontName.replace(/\s+/g, '+')}:wght@400;700&display=swap');`;
}

/**
 * Generate a complete typography system CSS for font pairing
 */
export function generatePairingCSS(
  headingFont: FontAnalysis,
  bodyFont: FontAnalysis,
  critique?: PairingCritique
): string {
  const headingSlug = toSlug(headingFont.fontName);
  const bodySlug = toSlug(bodyFont.fontName);

  return `/* Typography System - Font Pairing */
/* Generated by FontPair AI */
/* Heading: ${headingFont.fontName} | Body: ${bodyFont.fontName} */
${critique ? `/* Pairing Score: ${critique.overallScore}/10 */` : ''}

:root {
  /* Heading Font */
  --font-heading: "${headingFont.fontName}", ${headingFont.fontType.toLowerCase().includes('serif') && !headingFont.fontType.toLowerCase().includes('sans') ? 'serif' : 'sans-serif'};

  /* Body Font */
  --font-body: "${bodyFont.fontName}", ${bodyFont.fontType.toLowerCase().includes('serif') && !bodyFont.fontType.toLowerCase().includes('sans') ? 'serif' : 'sans-serif'};

  /* Type Scale (Major Third - 1.25) */
  --text-xs: 0.64rem;
  --text-sm: 0.8rem;
  --text-base: 1rem;
  --text-lg: 1.25rem;
  --text-xl: 1.563rem;
  --text-2xl: 1.953rem;
  --text-3xl: 2.441rem;
  --text-4xl: 3.052rem;
}

/* Base Typography */
body {
  font-family: var(--font-body);
  font-size: var(--text-base);
  line-height: 1.6;
}

/* Headings */
h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  line-height: 1.2;
  margin-bottom: 0.5em;
}

h1 { font-size: var(--text-4xl); font-weight: 700; }
h2 { font-size: var(--text-3xl); font-weight: 700; }
h3 { font-size: var(--text-2xl); font-weight: 600; }
h4 { font-size: var(--text-xl); font-weight: 600; }
h5 { font-size: var(--text-lg); font-weight: 600; }
h6 { font-size: var(--text-base); font-weight: 600; }

/* Body Text */
p {
  margin-bottom: 1em;
}

/* Small Text */
small, .text-small {
  font-size: var(--text-sm);
}

/* Caption */
.caption {
  font-size: var(--text-xs);
  color: #666;
}

/* Google Fonts Import */
@import url('https://fonts.googleapis.com/css2?family=${headingFont.fontName.replace(/\s+/g, '+')}:wght@400;600;700&family=${bodyFont.fontName.replace(/\s+/g, '+')}:wght@400;600;700&display=swap');`;
}

// Updated color scheme matching Typography Constitution
const COLORS = {
  paper: '#F5F2EB',           // Paper background
  ink: '#1A3431',             // Dark green for main text  
  teal: '#004d4d',            // Teal for headings (Darker Teal from Constitution)
  accent: '#FF8E24',          // Orange accent
  muted: '#555555',           // Muted text
  accentSoft: '#FFF4E6'       // Very light orange for backgrounds (solid hex for PDF reliability)
};

// Logo loading function
const loadLogo = async (): Promise<{ dataUrl: string; width: number; height: number } | null> => {
  try {
    const response = await fetch('logo-full.svg');
    if (!response.ok) return null;
    const svgText = await response.text();
    
    // Create an image from the SVG
    const img = new Image();
    const svgBlob = new Blob([svgText], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);
    
    return new Promise((resolve) => {
      img.onload = () => {
        const canvas = document.createElement('canvas');
        // Scale up for better quality in PDF
        const scale = 3;
        canvas.width = img.width * scale;
        canvas.height = img.height * scale;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
          resolve({
              dataUrl: canvas.toDataURL('image/png'),
              width: img.width,
              height: img.height
          });
        } else {
          resolve(null);
        }
        URL.revokeObjectURL(url);
      };
      img.onerror = () => {
        resolve(null);
        URL.revokeObjectURL(url);
      };
      img.src = url;
    });
  } catch (e) {
    console.error("Failed to load logo:", e);
    return null;
  }
};

export async function exportAnalysisToPDF(analysis: FontAnalysis, previewImageBase64?: string): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Load logo first
  const logoData = await loadLogo();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25;
  const contentWidth = pageWidth - (2 * margin);
  let yPosition = margin;

  // Helper function to add a new page with proper formatting
  const addNewPage = () => {
    doc.addPage();
    yPosition = margin + 15;
    
    // Add subtle header line on new pages 
    doc.setDrawColor(COLORS.accent);
    doc.setLineWidth(0.5);
    doc.line(margin, 12, pageWidth - margin, 12);
  };

  const checkAndAddPage = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - 25) {
      addNewPage();
      return true;
    }
    return false;
  };

  const splitText = (text: string, maxWidth: number, fontSize: number) => {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text, maxWidth);
  };

  // ===== PAGE 1: COVER PAGE =====
  
  // Top accent bar
  doc.setFillColor(COLORS.accent);
  doc.rect(0, 0, pageWidth, 8, 'F');
  
  // Paper background for content area
  doc.setFillColor(COLORS.paper);
  doc.rect(0, 8, pageWidth, pageHeight - 16, 'F');
  
  // Bottom accent bar
  doc.setFillColor(COLORS.accent);
  doc.rect(0, pageHeight - 8, pageWidth, 8, 'F');

  // Draw Logo
  if (logoData) {
    // Calculate dimensions preserving aspect ratio
    const targetWidth = 80; // Wider logo on cover
    const aspectRatio = logoData.height / logoData.width;
    const targetHeight = targetWidth * aspectRatio;
    
    const logoX = (pageWidth - targetWidth) / 2;
    const logoY = 30; // Adjusted position
    
    doc.addImage(logoData.dataUrl, 'PNG', logoX, logoY, targetWidth, targetHeight);
    

  } else {
    // Fallback text if logo fails
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.setTextColor(COLORS.ink);
    doc.text('FontPair AI', pageWidth / 2, 60, { align: 'center' });
  }
  
  // Main title: Font Name
  yPosition = 120;
  doc.setFont('times', 'bold'); // Serif for headings per Constitution style
  doc.setFontSize(36);
  doc.setTextColor(COLORS.ink);
  const fontNameLines = splitText(analysis.fontName, contentWidth, 36);
  fontNameLines.forEach((line: string) => {
    doc.text(line, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 16;
  });
  
  // Decorative line UNDER title (similar to H1 border-bottom)
  doc.setDrawColor(COLORS.accent);
  doc.setLineWidth(1.5); // Thicker line for H1
  // Draw line 5px below the last title line baseline
  doc.line(pageWidth / 2 - 50, yPosition - 8, pageWidth / 2 + 50, yPosition - 8);
  
  yPosition += 10; // Space after line
  
  // Subtitle: Font Type
  doc.setFont('helvetica', 'italic'); // Sans-serif italic for contrast
  doc.setFontSize(18);
  doc.setTextColor(COLORS.teal); // Teal color for subtitle
  doc.text(analysis.fontType, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 25;
  
  // Designer info
  if (analysis.designer && analysis.designer.toLowerCase() !== 'unknown designer') {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(COLORS.muted);
    doc.text(`Designed by ${analysis.designer}`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 10;
  }
  
  // Variable font badge
  if (analysis.isVariable) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(COLORS.accent);
    doc.text('[VARIABLE FONT]', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 10;
  }
  
  // Preview image on cover page
  if (previewImageBase64) {
    yPosition += 10;
    try {
      const img = new Image();
      img.src = previewImageBase64;
      await new Promise((resolve) => {
        img.onload = resolve;
        setTimeout(resolve, 1000);
      });

      const actualWidth = img.width || 800;
      const actualHeight = img.height || 200;
      const aspectRatio = actualHeight / actualWidth;

      let imgWidth = contentWidth * 0.7;
      let imgHeight = imgWidth * aspectRatio;

      if (imgHeight > 60) {
        imgHeight = 60;
        imgWidth = imgHeight / aspectRatio;
      }

      const imgX = (pageWidth - imgWidth) / 2;
      
      // Add subtle border around preview
      doc.setDrawColor(COLORS.teal);
      doc.setLineWidth(0.3);
      doc.roundedRect(imgX - 2, yPosition - 2, imgWidth + 4, imgHeight + 4, 2, 2, 'S');
      
      doc.addImage(previewImageBase64, 'PNG', imgX, yPosition, imgWidth, imgHeight);
      yPosition += imgHeight + 15;
    } catch (e) {
      console.error('Failed to add preview image', e);
    }
  }
  
  // Tagline at bottom of cover
  doc.text('Font Analysis Report', pageWidth / 2, pageHeight - 35, { align: 'center' });
  doc.text('AI-Powered Analysis Report', pageWidth / 2, pageHeight - 28, { align: 'center' });

  // ===== PAGE 2+: CONTENT PAGES =====
  addNewPage();
  
  // Section helper with Typography Constitution styling
  const addSection = (title: string, content: string | string[], isList: boolean = false) => {
    checkAndAddPage(25);

    // Section title with accent color
    doc.setFont('helvetica', 'bold'); // Sans-serif headings
    doc.setFontSize(14);
    doc.setTextColor(COLORS.accent);
    doc.text(title, margin, yPosition);
    yPosition += 8;

    // Content in dark ink, serif body
    doc.setFont('times', 'roman');
    doc.setFontSize(11);
    doc.setTextColor(COLORS.ink);

    if (isList && Array.isArray(content)) {
      content.forEach(item => {
        checkAndAddPage(12);
        // Orange bullet
        doc.setFillColor(COLORS.accent);
        doc.circle(margin + 3, yPosition - 1.5, 1, 'F');
        const lines = splitText(item, contentWidth - 10, 11);
        doc.text(lines, margin + 8, yPosition);
        yPosition += lines.length * 5 + 3;
      });
    } else {
      const text = Array.isArray(content) ? content.join(', ') : content;
      const lines = splitText(text, contentWidth, 11);
      lines.forEach((line: string) => {
        checkAndAddPage(7);
        doc.text(line, margin, yPosition);
        yPosition += 6;
      });
    }

    yPosition += 10;
  };

  // Blockquote style for analysis (like Typography Constitution abstract)
  const addBlockquote = (content: string) => {
    checkAndAddPage(30);
    
    // Background box - Light Orange
    doc.setFillColor(COLORS.accentSoft); 
    const textLines = splitText(content, contentWidth - 20, 11);
    const boxHeight = textLines.length * 6 + 16;
    doc.roundedRect(margin, yPosition - 4, contentWidth, boxHeight, 2, 2, 'F');
    
    // Left accent bar
    doc.setFillColor(COLORS.accent);
    doc.rect(margin, yPosition - 4, 3, boxHeight, 'F');
    
    // Text - Dark Grey/Muted
    doc.setFont('times', 'italic'); // Serif italic
    doc.setFontSize(11);
    doc.setTextColor(COLORS.muted); // Dark grey for readability on light orange
    textLines.forEach((line: string) => {
      doc.text(line, margin + 10, yPosition + 6);
      yPosition += 6;
    });
    
    // Add Extra Spacing after box
    yPosition += 20; // Increased spacing to prevent overlap
  };

  // Main Analysis in blockquote style
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(COLORS.ink);
  doc.text('Analysis', margin, yPosition);
  yPosition += 6;
  // Underline for Analysis Header
  doc.setDrawColor(COLORS.accent);
  doc.setLineWidth(1);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;
  
  addBlockquote(analysis.analysis);

  // Historical Context
  if (analysis.historicalContext) {
    addSection('Historical Context', analysis.historicalContext);
  }

  // Accessibility & Legibility
  if (analysis.accessibility) {
    checkAndAddPage(25);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(COLORS.accent);
    doc.text('Accessibility & Legibility', margin, yPosition);
    yPosition += 8;

    doc.setFont('times', 'roman');
    doc.setFontSize(11);
    doc.setTextColor(COLORS.ink);
    const accessLines = splitText(analysis.accessibility.analysis, contentWidth, 11);
    accessLines.forEach((line: string) => {
      checkAndAddPage(7);
      doc.text(line, margin, yPosition);
      yPosition += 6;
    });
    yPosition += 5;

    if (analysis.accessibility.notes && analysis.accessibility.notes.length > 0) {
      analysis.accessibility.notes.forEach(note => {
        checkAndAddPage(12);
        doc.setFillColor(COLORS.accent);
        doc.circle(margin + 3, yPosition - 1.5, 1, 'F');
        const lines = splitText(note, contentWidth - 10, 11);
        doc.text(lines, margin + 8, yPosition);
        yPosition += lines.length * 6 + 3;
      });
    }
    yPosition += 8;
  }

  // Font Pairing Suggestions
  if (analysis.fontPairings && analysis.fontPairings.length > 0) {
    checkAndAddPage(25);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(COLORS.accent);
    doc.text('Font Pairing Suggestions', margin, yPosition);
    yPosition += 10;

    analysis.fontPairings.forEach((pairing, index) => {
      checkAndAddPage(20);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(COLORS.ink);
      doc.text(`${index + 1}. ${pairing.primary} + ${pairing.secondary}`, margin, yPosition);
      yPosition += 6;

      doc.setFont('times', 'roman');
      doc.setFontSize(11);
      doc.setTextColor(COLORS.muted);
      const rationaleLines = splitText(pairing.rationale, contentWidth - 5, 11);
      rationaleLines.forEach((line: string) => {
        checkAndAddPage(7);
        doc.text(line, margin + 5, yPosition);
        yPosition += 6;
      });
      yPosition += 5;
    });
    yPosition += 5;
  }

  // Similar Font Alternatives
  if (analysis.similarFonts && analysis.similarFonts.length > 0) {
    checkAndAddPage(25);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(COLORS.accent);
    doc.text('Similar Font Alternatives', margin, yPosition);
    yPosition += 10;

    analysis.similarFonts.forEach((font, index) => {
      checkAndAddPage(18);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(COLORS.ink);
      doc.text(`${index + 1}. ${font.name}`, margin, yPosition);

      doc.setFont('times', 'italic');
      doc.setFontSize(10);
      doc.setTextColor(COLORS.teal);
      const fontNameText = `${index + 1}. ${font.name}`;
      doc.setFont('helvetica', 'bold'); // Reset to bold to measure correctly
      doc.setFontSize(12);
      const nameWidth = doc.getTextWidth(fontNameText);
      doc.setFont('times', 'italic');
      doc.setFontSize(10);
      doc.text(` (${font.source})`, margin + nameWidth + 2, yPosition);
      yPosition += 6;

      doc.setFont('times', 'roman');
      doc.setFontSize(11);
      doc.setTextColor(COLORS.muted);
      const rationaleLines = splitText(font.rationale, contentWidth - 5, 11);
      rationaleLines.forEach((line: string) => {
        checkAndAddPage(7);
        doc.text(line, margin + 5, yPosition);
        yPosition += 6;
      });
      yPosition += 5;
    });
    yPosition += 5;
  }

  // Recommended Usage
  if (analysis.usageRecommendations && analysis.usageRecommendations.length > 0) {
    addSection('Recommended Usage', analysis.usageRecommendations, true);
  }

  // Weight Recommendations
  if (analysis.weightRecommendations && analysis.weightRecommendations.length > 0) {
    addSection('Weight Recommendations', analysis.weightRecommendations, true);
  }

  // Business Suitability
  if (analysis.businessSuitability && analysis.businessSuitability.length > 0) {
    checkAndAddPage(20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(COLORS.accent);
    doc.text('Business Suitability', margin, yPosition);
    yPosition += 8;

    doc.setFont('times', 'roman');
    doc.setFontSize(11);
    doc.setTextColor(COLORS.ink);
    const businessText = analysis.businessSuitability.join(' • ');
    const businessLines = splitText(businessText, contentWidth, 11);
    businessLines.forEach((line: string) => {
      checkAndAddPage(7);
      doc.text(line, margin, yPosition);
      yPosition += 6;
    });
    yPosition += 8;
  }

  // License Information
  if (analysis.licenseInfo) {
    addSection('License & Usage Information', analysis.licenseInfo);
  }

  if (analysis.licensingNotes) {
    addSection('Commercial Licensing Notes', analysis.licensingNotes);
  }

  // Character Set Support
  if (analysis.characterSets && analysis.characterSets.length > 0) {
    checkAndAddPage(20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(COLORS.accent);
    doc.text('Character Set Support', margin, yPosition);
    yPosition += 8;

    doc.setFont('times', 'roman');
    doc.setFontSize(11);
    doc.setTextColor(COLORS.ink);
    const charSetText = analysis.characterSets.join(' • ');
    const charSetLines = splitText(charSetText, contentWidth, 11);
    charSetLines.forEach((line: string) => {
      checkAndAddPage(7);
      doc.text(line, margin, yPosition);
      yPosition += 6;
    });
    yPosition += 8;
  }

  // Release Year
  if (analysis.releaseYear && analysis.releaseYear.toLowerCase() !== 'unknown') {
    checkAndAddPage(12);
    doc.setFont('times', 'italic');
    doc.setFontSize(11);
    doc.setTextColor(COLORS.muted);
    doc.text(`Originally released: ${analysis.releaseYear}`, margin, yPosition);
    yPosition += 10;
  }

  // Add bottom accent bar on last page
  doc.setFillColor(COLORS.accent);
  doc.rect(0, pageHeight - 8, pageWidth, 8, 'F');

  // Add watermark for free tier users
  if (!isProfessional()) {
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setTextColor(150, 150, 150); // Light gray
      doc.setFontSize(40);
      doc.setFont('helvetica', 'bold');
      
      const text = "FONTPAIR AI - FREE VERSION";
      
      // Center the text at 45 degrees
      const x = pageWidth / 2;
      const y = pageHeight / 2;
      
      // Save graphics state
      // @ts-ignore - context2d property exists on internal but typescript definitions might miss it for some versions
      if (doc.context2d) {
          doc.saveGraphicsState();
          doc.setGState(new doc.GState({ opacity: 0.15 })); // Set opacity if possible
      }

      doc.text(text, x, y, { align: 'center', angle: 45 });

      if (doc.context2d) {
          doc.restoreGraphicsState();
      }
    }
  }

  // Footer
  doc.setFont('times', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(COLORS.muted);
  const footerText = 'A FontPair AI Analysis Report • Powered by Gemini';
  doc.text(footerText, pageWidth / 2, pageHeight - 14, { align: 'center' });

  // Save the PDF
  const fileName = `${analysis.fontName.replace(/\s+/g, '_')}_Analysis.pdf`;
  doc.save(fileName);
}