import type { FontAnalysis, PairingCritique } from './types';
import { jsPDF } from 'jspdf';

// Helper to convert font name to valid CSS variable name
const toSlug = (name: string): string => {
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
};

// Helper to extract weight number from recommendation string
const extractWeight = (rec: string): number => {
  const match = rec.match(/\d+/);
  return match ? parseInt(match[0], 10) : 400;
};

/**
 * Generate CSS variables for a font analysis
 */
export function generateCSSVariables(analysis: FontAnalysis): string {
  const slug = toSlug(analysis.fontName);
  const weights = analysis.weightRecommendations.map(rec => {
    const weight = extractWeight(rec);
    const label = rec.split(' ')[0].toLowerCase();
    return `  --font-weight-${slug}-${label}: ${weight};`;
  });

  return `/* ${analysis.fontName} - CSS Variables */
/* Generated by FontPair AI */

:root {
  /* Font Family */
  --font-family-${slug}: "${analysis.fontName}", ${analysis.fontType.toLowerCase().includes('serif') && !analysis.fontType.toLowerCase().includes('sans') ? 'serif' : 'sans-serif'};

  /* Font Weights */
${weights.join('\n')}

  /* Usage Notes */
  /* Type: ${analysis.fontType} */
  /* Designer: ${analysis.designer} */
  /* Best for: ${analysis.usageRecommendations.slice(0, 2).join(', ')} */
}

/* Example Usage */
.heading-${slug} {
  font-family: var(--font-family-${slug});
  font-weight: var(--font-weight-${slug}-bold, 700);
}

.body-${slug} {
  font-family: var(--font-family-${slug});
  font-weight: var(--font-weight-${slug}-regular, 400);
}`;
}

/**
 * Generate Tailwind CSS config for a font analysis
 */
export function generateTailwindConfig(analysis: FontAnalysis): string {
  const slug = toSlug(analysis.fontName);
  const fallback = analysis.fontType.toLowerCase().includes('serif') && !analysis.fontType.toLowerCase().includes('sans')
    ? 'ui-serif, Georgia, serif'
    : 'ui-sans-serif, system-ui, sans-serif';

  return `// ${analysis.fontName} - Tailwind CSS Configuration
// Generated by FontPair AI

// Add to your tailwind.config.js:

module.exports = {
  theme: {
    extend: {
      fontFamily: {
        '${slug}': ['"${analysis.fontName}"', '${fallback}'],
      },
      // Optional: Add as a font weight utility
      fontWeight: {
        // Based on analysis recommendations
${analysis.weightRecommendations.map(rec => {
  const weight = extractWeight(rec);
  const label = rec.split(' ')[0].toLowerCase();
  return `        '${slug}-${label}': '${weight}',`;
}).join('\n')}
      },
    },
  },
}

// Usage in your HTML/JSX:
// <h1 class="font-${slug} font-bold">Heading</h1>
// <p class="font-${slug}">Body text</p>

// Don't forget to import the font in your CSS:
// @import url('https://fonts.googleapis.com/css2?family=${analysis.fontName.replace(/\s+/g, '+')}:wght@400;700&display=swap');`;
}

/**
 * Generate a complete typography system CSS for font pairing
 */
export function generatePairingCSS(
  headingFont: FontAnalysis,
  bodyFont: FontAnalysis,
  critique?: PairingCritique
): string {
  const headingSlug = toSlug(headingFont.fontName);
  const bodySlug = toSlug(bodyFont.fontName);

  return `/* Typography System - Font Pairing */
/* Generated by FontPair AI */
/* Heading: ${headingFont.fontName} | Body: ${bodyFont.fontName} */
${critique ? `/* Pairing Score: ${critique.overallScore}/10 */` : ''}

:root {
  /* Heading Font */
  --font-heading: "${headingFont.fontName}", ${headingFont.fontType.toLowerCase().includes('serif') && !headingFont.fontType.toLowerCase().includes('sans') ? 'serif' : 'sans-serif'};

  /* Body Font */
  --font-body: "${bodyFont.fontName}", ${bodyFont.fontType.toLowerCase().includes('serif') && !bodyFont.fontType.toLowerCase().includes('sans') ? 'serif' : 'sans-serif'};

  /* Type Scale (Major Third - 1.25) */
  --text-xs: 0.64rem;
  --text-sm: 0.8rem;
  --text-base: 1rem;
  --text-lg: 1.25rem;
  --text-xl: 1.563rem;
  --text-2xl: 1.953rem;
  --text-3xl: 2.441rem;
  --text-4xl: 3.052rem;
}

/* Base Typography */
body {
  font-family: var(--font-body);
  font-size: var(--text-base);
  line-height: 1.6;
}

/* Headings */
h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  line-height: 1.2;
  margin-bottom: 0.5em;
}

h1 { font-size: var(--text-4xl); font-weight: 700; }
h2 { font-size: var(--text-3xl); font-weight: 700; }
h3 { font-size: var(--text-2xl); font-weight: 600; }
h4 { font-size: var(--text-xl); font-weight: 600; }
h5 { font-size: var(--text-lg); font-weight: 600; }
h6 { font-size: var(--text-base); font-weight: 600; }

/* Body Text */
p {
  margin-bottom: 1em;
}

/* Small Text */
small, .text-small {
  font-size: var(--text-sm);
}

/* Caption */
.caption {
  font-size: var(--text-xs);
  color: #666;
}

/* Google Fonts Import */
@import url('https://fonts.googleapis.com/css2?family=${headingFont.fontName.replace(/\s+/g, '+')}:wght@400;600;700&family=${bodyFont.fontName.replace(/\s+/g, '+')}:wght@400;600;700&display=swap');`;
}

// Print-friendly color scheme with paper background
const COLORS = {
  background: '#F2EFE8',   // Light paper color (no pure white)
  primary: '#1A3431',      // Dark green for main text
  secondary: '#2D4E4A',    // Medium dark green for supporting text
  accent: '#FF8E24'        // Orange for highlights
};

export async function exportAnalysisToPDF(analysis: FontAnalysis, previewImageBase64?: string): Promise<void> {
  // Use jsPDF from npm package
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (2 * margin);
  let yPosition = margin;

  // Helper function to add a new page if needed
  const checkAndAddPage = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Helper function to wrap text
  const splitText = (text: string, maxWidth: number, fontSize: number) => {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text, maxWidth);
  };

  // Header with accent bar
  doc.setFillColor(COLORS.accent);
  doc.rect(0, 0, pageWidth, 15, 'F');

  // Light paper text on orange background
  doc.setTextColor('#F2EFE8');
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('FontPair AI', margin, 10);

  yPosition = 25;

  // Font Name and Type
  doc.setTextColor(COLORS.primary);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  const fontNameLines = splitText(analysis.fontName, contentWidth, 24);
  doc.text(fontNameLines, margin, yPosition);
  yPosition += fontNameLines.length * 10;

  doc.setTextColor(COLORS.accent);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(analysis.fontType, margin, yPosition);
  yPosition += 8;

  if (analysis.designer && analysis.designer.toLowerCase() !== 'unknown designer') {
    doc.setTextColor(COLORS.secondary);
    doc.setFontSize(11);
    doc.text(`by ${analysis.designer}`, margin, yPosition);
    yPosition += 8;
  }

  if (analysis.isVariable) {
    doc.setTextColor(COLORS.accent);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('[VARIABLE FONT]', margin, yPosition);
    yPosition += 8;
  }

  yPosition += 5;

  // Preview Image (if provided)
  if (previewImageBase64) {
    checkAndAddPage(90);
    doc.setTextColor(COLORS.accent);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Preview', margin, yPosition);
    yPosition += 7;

    try {
      // Load image to get actual dimensions
      const img = new Image();
      img.src = previewImageBase64;

      // Calculate proper aspect ratio to prevent squashing
      await new Promise((resolve) => {
        img.onload = resolve;
        // Set a timeout in case image doesn't load
        setTimeout(resolve, 1000);
      });

      const actualWidth = img.width || 800;
      const actualHeight = img.height || 200;
      const aspectRatio = actualHeight / actualWidth;

      // Calculate dimensions maintaining aspect ratio
      const maxWidth = contentWidth;
      const maxHeight = 80; // Max height in mm

      let imgWidth = maxWidth;
      let imgHeight = imgWidth * aspectRatio;

      // If calculated height exceeds max, scale down
      if (imgHeight > maxHeight) {
        imgHeight = maxHeight;
        imgWidth = imgHeight / aspectRatio;
      }

      doc.addImage(previewImageBase64, 'PNG', margin, yPosition, imgWidth, imgHeight);
      yPosition += imgHeight + 10;
    } catch (e) {
      console.error('Failed to add preview image', e);
    }
  }

  // Section helper function
  const addSection = (title: string, content: string | string[], isList: boolean = false) => {
    checkAndAddPage(20);

    doc.setTextColor(COLORS.accent);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, yPosition);
    yPosition += 7;

    doc.setTextColor(COLORS.primary);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    if (isList && Array.isArray(content)) {
      content.forEach(item => {
        checkAndAddPage(10);
        const bulletX = margin + 2;
        doc.circle(bulletX, yPosition - 1.5, 0.8, 'F');
        const lines = splitText(item, contentWidth - 8, 10);
        doc.text(lines, margin + 6, yPosition);
        yPosition += lines.length * 5 + 2;
      });
    } else {
      const text = Array.isArray(content) ? content.join(', ') : content;
      const lines = splitText(text, contentWidth, 10);
      lines.forEach((line: string) => {
        checkAndAddPage(7);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
    }

    yPosition += 5;
  };

  // Analysis
  addSection('Analysis', analysis.analysis);

  // Historical Context
  if (analysis.historicalContext) {
    addSection('Historical Context', analysis.historicalContext);
  }

  // Accessibility & Legibility
  if (analysis.accessibility) {
    checkAndAddPage(20);
    doc.setTextColor(COLORS.accent);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Accessibility & Legibility', margin, yPosition);
    yPosition += 7;

    doc.setTextColor(COLORS.primary);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const accessLines = splitText(analysis.accessibility.analysis, contentWidth, 10);
    accessLines.forEach((line: string) => {
      checkAndAddPage(7);
      doc.text(line, margin, yPosition);
      yPosition += 5;
    });
    yPosition += 3;

    if (analysis.accessibility.notes && analysis.accessibility.notes.length > 0) {
      analysis.accessibility.notes.forEach(note => {
        checkAndAddPage(10);
        const bulletX = margin + 2;
        doc.setFillColor(COLORS.accent);
        doc.circle(bulletX, yPosition - 1.5, 0.8, 'F');
        const lines = splitText(note, contentWidth - 8, 10);
        doc.text(lines, margin + 6, yPosition);
        yPosition += lines.length * 5 + 2;
      });
    }
    yPosition += 5;
  }

  // Font Pairing Suggestions
  if (analysis.fontPairings && analysis.fontPairings.length > 0) {
    checkAndAddPage(20);
    doc.setTextColor(COLORS.accent);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Font Pairing Suggestions', margin, yPosition);
    yPosition += 7;

    analysis.fontPairings.forEach((pairing, index) => {
      checkAndAddPage(15);
      doc.setTextColor(COLORS.primary);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${pairing.primary} + ${pairing.secondary}`, margin, yPosition);
      yPosition += 5;

      doc.setFont('helvetica', 'normal');
      const rationaleLines = splitText(pairing.rationale, contentWidth, 10);
      rationaleLines.forEach((line: string) => {
        checkAndAddPage(7);
        doc.text(line, margin + 5, yPosition);
        yPosition += 5;
      });
      yPosition += 3;
    });
    yPosition += 5;
  }

  // Similar Font Alternatives
  if (analysis.similarFonts && analysis.similarFonts.length > 0) {
    checkAndAddPage(20);
    doc.setTextColor(COLORS.accent);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Similar Font Alternatives', margin, yPosition);
    yPosition += 7;

    analysis.similarFonts.forEach((font, index) => {
      checkAndAddPage(12);
      doc.setTextColor(COLORS.primary);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${font.name}`, margin, yPosition);

      doc.setTextColor(COLORS.secondary);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.text(`(${font.source})`, margin + doc.getTextWidth(`${index + 1}. ${font.name}`) + 2, yPosition);
      yPosition += 5;

      doc.setTextColor(COLORS.primary);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const rationaleLines = splitText(font.rationale, contentWidth, 10);
      rationaleLines.forEach((line: string) => {
        checkAndAddPage(7);
        doc.text(line, margin + 5, yPosition);
        yPosition += 5;
      });
      yPosition += 3;
    });
    yPosition += 5;
  }

  // Recommended Usage
  if (analysis.usageRecommendations && analysis.usageRecommendations.length > 0) {
    addSection('Recommended Usage', analysis.usageRecommendations, true);
  }

  // Weight Recommendations
  if (analysis.weightRecommendations && analysis.weightRecommendations.length > 0) {
    addSection('Weight Recommendations', analysis.weightRecommendations, true);
  }

  // Business Suitability
  if (analysis.businessSuitability && analysis.businessSuitability.length > 0) {
    checkAndAddPage(15);
    doc.setTextColor(COLORS.accent);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Business Suitability', margin, yPosition);
    yPosition += 7;

    doc.setTextColor(COLORS.primary);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(analysis.businessSuitability.join(', '), margin, yPosition, { maxWidth: contentWidth });
    const businessLines = splitText(analysis.businessSuitability.join(', '), contentWidth, 10);
    yPosition += businessLines.length * 5 + 5;
  }

  // License & Usage Information
  if (analysis.licenseInfo) {
    addSection('License & Usage Information', analysis.licenseInfo);
  }

  // Licensing Notes for Commercial Use (new field)
  if (analysis.licensingNotes) {
    addSection('Commercial Licensing Notes', analysis.licensingNotes);
  }

  // Character Set Support (new field)
  if (analysis.characterSets && analysis.characterSets.length > 0) {
    checkAndAddPage(15);
    doc.setTextColor(COLORS.accent);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Character Set Support', margin, yPosition);
    yPosition += 7;

    doc.setTextColor(COLORS.primary);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const charSetText = analysis.characterSets.join(' • ');
    const charSetLines = splitText(charSetText, contentWidth, 10);
    charSetLines.forEach((line: string) => {
      checkAndAddPage(7);
      doc.text(line, margin, yPosition);
      yPosition += 5;
    });
    yPosition += 5;
  }

  // Release Year (new field)
  if (analysis.releaseYear && analysis.releaseYear.toLowerCase() !== 'unknown') {
    checkAndAddPage(10);
    doc.setTextColor(COLORS.secondary);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.text(`Originally released: ${analysis.releaseYear}`, margin, yPosition);
    yPosition += 8;
  }

  // Footer on last page
  doc.setTextColor(COLORS.secondary);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  const footerText = 'Generated by FontPair AI - Powered by Google Gemini';
  const footerWidth = doc.getTextWidth(footerText);
  doc.text(footerText, (pageWidth - footerWidth) / 2, pageHeight - 10);

  // Save the PDF
  const fileName = `${analysis.fontName.replace(/\s+/g, '_')}_Analysis.pdf`;
  doc.save(fileName);
}
