import React, { useState, useEffect } from 'react';
import type { FontAnalysis } from '../types';
import { generatePairingCSS } from '../pdfExportService';
import { CopyIcon, CheckIcon } from './Icons';

interface TypeLevel {
    id: string;
    label: string;
    size: string;
    weight: number;
    lineHeight: number;
    sampleText: string;
}

const TYPE_LEVELS: TypeLevel[] = [
    { id: 'h1', label: 'H1', size: '3.052rem', weight: 700, lineHeight: 1.1, sampleText: 'Main Headline' },
    { id: 'h2', label: 'H2', size: '2.441rem', weight: 700, lineHeight: 1.2, sampleText: 'Section Title' },
    { id: 'h3', label: 'H3', size: '1.953rem', weight: 600, lineHeight: 1.2, sampleText: 'Subsection Header' },
    { id: 'h4', label: 'H4', size: '1.563rem', weight: 600, lineHeight: 1.3, sampleText: 'Card Title' },
    { id: 'h5', label: 'H5', size: '1.25rem', weight: 600, lineHeight: 1.4, sampleText: 'Small Heading' },
    { id: 'body', label: 'Body', size: '1rem', weight: 400, lineHeight: 1.6, sampleText: 'Body text appears here. This is the main reading content for paragraphs and long-form text.' },
    { id: 'small', label: 'Small', size: '0.875rem', weight: 400, lineHeight: 1.5, sampleText: 'Smaller supporting text' },
    { id: 'caption', label: 'Caption', size: '0.75rem', weight: 400, lineHeight: 1.4, sampleText: 'Caption or label text' },
];

interface TypeScaleBuilderProps {
    isOpen: boolean;
    onClose: () => void;
    availableFonts: FontAnalysis[];
}

const TypeScaleBuilder: React.FC<TypeScaleBuilderProps> = ({ isOpen, onClose, availableFonts }) => {
    const [assignments, setAssignments] = useState<Record<string, FontAnalysis | null>>({
        h1: null,
        h2: null,
        h3: null,
        h4: null,
        h5: null,
        body: null,
        small: null,
        caption: null,
    });

    const [loadedFonts, setLoadedFonts] = useState<Set<string>>(new Set());
    const [copied, setCopied] = useState(false);
    const [exportFormat, setExportFormat] = useState<'css' | 'tailwind'>('css');

    // Load Google Fonts for preview
    const loadGoogleFont = (fontName: string) => {
        if (!fontName || loadedFonts.has(fontName)) return;
        const fontUrl = `https://fonts.googleapis.com/css2?family=${fontName.replace(/ /g, '+')}:wght@400;600;700&display=swap`;
        if (document.querySelector(`link[href="${fontUrl}"]`)) return;

        const link = document.createElement('link');
        link.rel = 'stylesheet';
        link.href = fontUrl;
        document.head.appendChild(link);
        setLoadedFonts(prev => new Set(prev).add(fontName));
    };

    // Load fonts when assignments change
    useEffect(() => {
        Object.values(assignments).forEach(font => {
            if (font) loadGoogleFont(font.fontName);
        });
    }, [assignments]);

    const handleAssignment = (levelId: string, fontIndex: number) => {
        if (fontIndex === -1) {
            setAssignments(prev => ({ ...prev, [levelId]: null }));
        } else {
            setAssignments(prev => ({ ...prev, [levelId]: availableFonts[fontIndex] }));
        }
    };

    const generateCSS = (): string => {
        const lines: string[] = [
            '/* Typography System - Type Scale */',
            '/* Generated by FontPair AI */',
            '',
            ':root {',
            '  /* Type Scale (Major Third - 1.25) */',
            '  --text-xs: 0.75rem;',
            '  --text-sm: 0.875rem;',
            '  --text-base: 1rem;',
            '  --text-lg: 1.25rem;',
            '  --text-xl: 1.563rem;',
            '  --text-2xl: 1.953rem;',
            '  --text-3xl: 2.441rem;',
            '  --text-4xl: 3.052rem;',
            '',
        ];

        // Add font family variables
        const usedFonts = new Set<string>();
        Object.entries(assignments).forEach(([level, font]) => {
            if (font) {
                usedFonts.add(font.fontName);
                const fallback = font.fontType.toLowerCase().includes('serif') && !font.fontType.toLowerCase().includes('sans')
                    ? 'serif'
                    : 'sans-serif';
                lines.push(`  --font-${level}: "${font.fontName}", ${fallback};`);
            }
        });

        lines.push('}', '');

        // Add element styles
        TYPE_LEVELS.forEach(level => {
            const font = assignments[level.id];
            if (font) {
                if (level.id.startsWith('h')) {
                    lines.push(`${level.id} {`);
                    lines.push(`  font-family: var(--font-${level.id});`);
                    lines.push(`  font-size: ${level.size};`);
                    lines.push(`  font-weight: ${level.weight};`);
                    lines.push(`  line-height: ${level.lineHeight};`);
                    lines.push('}', '');
                } else if (level.id === 'body') {
                    lines.push('body, p {');
                    lines.push(`  font-family: var(--font-body);`);
                    lines.push(`  font-size: ${level.size};`);
                    lines.push(`  font-weight: ${level.weight};`);
                    lines.push(`  line-height: ${level.lineHeight};`);
                    lines.push('}', '');
                } else {
                    lines.push(`.${level.id} {`);
                    lines.push(`  font-family: var(--font-${level.id});`);
                    lines.push(`  font-size: ${level.size};`);
                    lines.push(`  font-weight: ${level.weight};`);
                    lines.push(`  line-height: ${level.lineHeight};`);
                    lines.push('}', '');
                }
            }
        });

        // Add Google Fonts import
        if (usedFonts.size > 0) {
            const fontImports = Array.from(usedFonts)
                .map(f => `family=${f.replace(/\s+/g, '+')}:wght@400;600;700`)
                .join('&');
            lines.push(`/* Google Fonts Import */`);
            lines.push(`@import url('https://fonts.googleapis.com/css2?${fontImports}&display=swap');`);
        }

        return lines.join('\n');
    };

    const handleCopy = () => {
        const css = generateCSS();
        navigator.clipboard.writeText(css).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    if (!isOpen) return null;

    return (
        <div
            className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 animate-fade-in p-4"
            onClick={onClose}
        >
            <div
                className="bg-surface rounded-lg w-full max-w-6xl max-h-[90vh] overflow-hidden border border-border shadow-2xl flex flex-col"
                onClick={e => e.stopPropagation()}
            >
                {/* Header */}
                <div className="p-6 border-b border-border flex-shrink-0">
                    <div className="flex items-center justify-between">
                        <div>
                            <h2 className="text-2xl font-bold text-primary">Type Scale Builder</h2>
                            <p className="text-secondary text-sm mt-1">
                                Assign fonts to different typography levels and preview your complete type system
                            </p>
                        </div>
                        <button
                            onClick={onClose}
                            className="text-secondary hover:text-primary transition-colors p-2"
                            aria-label="Close modal"
                        >
                            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-6">
                    {availableFonts.length === 0 ? (
                        <div className="text-center py-12 text-secondary">
                            <p className="mb-4">No fonts analyzed yet.</p>
                            <p className="text-sm">Analyze some fonts first, then return here to build your type scale.</p>
                        </div>
                    ) : (
                        <div className="grid lg:grid-cols-2 gap-6">
                            {/* Assignment Panel */}
                            <div className="space-y-4">
                                <h3 className="text-lg font-semibold text-accent mb-4">Assign Fonts</h3>
                                {TYPE_LEVELS.map(level => (
                                    <div key={level.id} className="flex items-center gap-4">
                                        <span className="text-primary font-semibold w-20">{level.label}</span>
                                        <select
                                            value={assignments[level.id] ? availableFonts.indexOf(assignments[level.id]!) : -1}
                                            onChange={(e) => handleAssignment(level.id, parseInt(e.target.value))}
                                            className="flex-1 bg-teal-dark border border-teal-medium rounded-md px-3 py-2 text-text-light text-sm focus:outline-none focus:border-accent"
                                        >
                                            <option value={-1}>Select font...</option>
                                            {availableFonts.map((font, index) => (
                                                <option key={index} value={index}>
                                                    {font.fontName} ({font.fontType})
                                                </option>
                                            ))}
                                        </select>
                                    </div>
                                ))}

                                {/* Quick Actions */}
                                <div className="pt-4 border-t border-border">
                                    <p className="text-sm text-secondary mb-2">Quick Actions:</p>
                                    <div className="flex gap-2 flex-wrap">
                                        {availableFonts.length >= 1 && (
                                            <button
                                                onClick={() => {
                                                    const headingFont = availableFonts[0];
                                                    setAssignments(prev => ({
                                                        ...prev,
                                                        h1: headingFont,
                                                        h2: headingFont,
                                                        h3: headingFont,
                                                        h4: headingFont,
                                                        h5: headingFont,
                                                    }));
                                                }}
                                                className="px-3 py-1.5 text-xs bg-secondary/30 text-primary rounded-md hover:bg-secondary/50 transition-colors"
                                            >
                                                All Headings → {availableFonts[0].fontName}
                                            </button>
                                        )}
                                        {availableFonts.length >= 2 && (
                                            <button
                                                onClick={() => {
                                                    const bodyFont = availableFonts[1];
                                                    setAssignments(prev => ({
                                                        ...prev,
                                                        body: bodyFont,
                                                        small: bodyFont,
                                                        caption: bodyFont,
                                                    }));
                                                }}
                                                className="px-3 py-1.5 text-xs bg-secondary/30 text-primary rounded-md hover:bg-secondary/50 transition-colors"
                                            >
                                                All Body → {availableFonts[1].fontName}
                                            </button>
                                        )}
                                    </div>
                                </div>
                            </div>

                            {/* Preview Panel */}
                            <div className="bg-paper-light rounded-lg p-6 border border-text-secondary/20">
                                <h3 className="text-lg font-semibold text-text-dark mb-4">Preview</h3>
                                <div className="space-y-4">
                                    {TYPE_LEVELS.map(level => {
                                        const font = assignments[level.id];
                                        return (
                                            <div
                                                key={level.id}
                                                className="pb-3 border-b border-text-secondary/10 last:border-0"
                                                style={{
                                                    fontFamily: font ? `'${font.fontName}', sans-serif` : 'inherit',
                                                    fontSize: level.size,
                                                    fontWeight: level.weight,
                                                    lineHeight: level.lineHeight,
                                                    color: font ? '#2B2624' : '#999',
                                                }}
                                            >
                                                {level.sampleText}
                                                {!font && (
                                                    <span className="text-xs ml-2 text-secondary">
                                                        (No font assigned)
                                                    </span>
                                                )}
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                {/* Footer */}
                {availableFonts.length > 0 && (
                    <div className="p-4 border-t border-border flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <span className="text-sm text-secondary">Export as:</span>
                            <button
                                onClick={() => setExportFormat('css')}
                                className={`px-3 py-1 text-sm rounded ${
                                    exportFormat === 'css'
                                        ? 'bg-accent text-surface'
                                        : 'bg-secondary/30 text-primary'
                                }`}
                            >
                                CSS
                            </button>
                            <button
                                onClick={() => setExportFormat('tailwind')}
                                className={`px-3 py-1 text-sm rounded ${
                                    exportFormat === 'tailwind'
                                        ? 'bg-accent text-surface'
                                        : 'bg-secondary/30 text-primary'
                                }`}
                            >
                                Tailwind
                            </button>
                        </div>
                        <button
                            onClick={handleCopy}
                            className={`px-4 py-2 font-semibold rounded-lg flex items-center gap-2 transition-colors ${
                                copied
                                    ? 'bg-green-500 text-white'
                                    : 'bg-accent text-surface hover:opacity-90'
                            }`}
                        >
                            {copied ? <CheckIcon className="w-4 h-4" /> : <CopyIcon className="w-4 h-4" />}
                            {copied ? 'Copied!' : 'Copy CSS'}
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

export default TypeScaleBuilder;
